#!/bin/sh

if [ -z "$1" ]
then
   FD=$PWD
elif [ "$1" = "./" ]
then
   FD=$PWD
else
   FD=$PWD/$1
fi

#find $FD  -name "*.c" -or -name "*.h" -or -name "*.cpp" -or -name "*.S" -or -name "*.java" > ./cscope.files
find $FD  -name "*.c" -or -name "*.h" -or -name "*.cpp" > ./cscope.files

if [ $2 ]; then
	find $PWD/$2  -name "*.c" -or -name "*.h" -or -name "*.cpp" -or -name "*.S" -or -name "*.java" >> ./cscope.files
fi
if [ $3 ]; then
	find $PWD/$3  -name "*.c" -or -name "*.h" -or -name "*.cpp" -or -name "*.S" -or -name "*.java" >> ./cscope.files
fi
	

cscope -Rbqk -i  $PWD/cscope.files 
#cp cscope.out c++.out
#cscope -Rbqk -i  $PWD/cscope.files 
lookupfile
